title: Compétitions et pratiques informatique de l’universite Laval
title_short: CPI-UL
description: >
  Compétitions et pratiques informatique de l’universite Laval.
  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean congue enim
  ac arcu elementum eleifend. Donec magna quam, lacinia ac ornare nec, pharetra
  non velit. Praesent sollicitudin porttitor dolor ac bibendum.
slack: spyvscat5
github: CECILUL

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.html

markdown: kramdown
exclude:
  - README.md
  - package.json
  - node_modules
  - Gemfile
  - Gemfile.lock

plugins:
  - jekyll-seo-tag
